const app=document.querySelector('#app'), title=document.querySelector('#pageTitle'), week=document.querySelector('#weekSelect');
for(let i=1;i<=PLAN.weeks;i++)week.add(new Option(`Semana ${i}`,i));
let state={view:'dashboard',workout:1,week:1};
week.onchange=()=>{state.week=+week.value;render()};
document.querySelectorAll('.nav').forEach(n=>n.onclick=()=>{document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));n.classList.add('active');state.view=n.dataset.view;document.querySelector('.sidebar').classList.remove('open');render()});
document.querySelector('#menu').onclick=()=>document.querySelector('.sidebar').classList.toggle('open');
const workouts=()=>PLAN.workouts.map(w=>`<div class="workout-row" onclick="openWorkout(${w.id})"><span class="num">0${w.id}</span><div><b>${w.name}</b><small>${w.focus} · ${w.exercises.length} exercícios</small></div><span class="arrow">›</span></div>`).join('');
function openWorkout(id){state.workout=id;state.view='workouts';document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.view==='workouts'));render()}
function dashboard(){return `<div class="wrap"><div class="hero"><div><span class="pill">SEMANA ${state.week} · ${PLAN.goal.toUpperCase()}</span><h2>Continua a construir consistência.</h2><p>O teu plano está organizado e pronto para registares a próxima sessão.</p><button class="primary" onclick="openWorkout(1)">Ver treino →</button></div></div><div class="stats"><div class="stat"><small>TREINOS NO PLANO</small><strong>${PLAN.workouts.length}</strong><em>Importados do Excel</em></div><div class="stat"><small>EXERCÍCIOS</small><strong>${PLAN.workouts.reduce((a,w)=>a+w.exercises.length,0)}</strong><em>Estruturados</em></div><div class="stat"><small>FASE</small><strong>Hipertrofia</strong><em>+ Força</em></div><div class="stat"><small>INÍCIO DO PLANO</small><strong>05 Mai</strong><em>2025</em></div></div><div class="grid2"><div class="card"><h3>Treinos disponíveis</h3>${workouts()}</div><div class="card"><h3>Semana ${state.week}</h3><div class="weekbar">${['S','T','Q','Q','S','S','D'].map((d,i)=>`<div class="day ${i===0?'active':''}">${d}<b>${i+1}</b></div>`).join('')}</div><div class="note">Esta primeira versão já usa a estrutura do teu ficheiro <b>Peres 2025</b>. O registo das séries e histórico será ligado a estes exercícios.</div></div></div></div>`}
function workoutView(){let w=PLAN.workouts.find(x=>x.id===state.workout);return `<div class="wrap"><div class="sectionhead"><div><p class="eyebrow">SEMANA ${state.week}</p><h2>${w.name}</h2><p>${w.focus} · ${w.exercises.length} exercícios</p></div><button class="primary" onclick="alert('O modo de registo será a próxima funcionalidade a ligar.')">Iniciar treino</button></div><div class="workout-tabs">${PLAN.workouts.map(x=>`<button class="tab ${x.id===w.id?'active':''}" onclick="state.workout=${x.id};render()">${x.name}</button>`).join('')}</div><div class="card">${w.exercises.map((e,i)=>`<div class="exercise"><div><b>${i+1}. ${e.name}${e.warmup?'<span class="badge">BASE</span>':''}</b><small>${e.warmup?'Séries de preparação incluídas':'Exercício de trabalho'}</small></div><div class="metric"><label>Séries</label><span>${e.sets}</span></div><div class="metric"><label>Reps</label><span>${e.reps}</span></div><div class="metric"><label>Carga</label><span>${e.load}</span></div><div class="metric"><label>RPE</label><span>${e.rpe}</span></div><div class="metric"><label>Descanso</label><span>${e.rest}</span></div></div>`).join('')}</div></div>`}
function placeholder(name,icon,text){return `<div class="wrap"><div class="sectionhead"><div><h2>${name}</h2><p>Área preparada para a próxima fase.</p></div></div><div class="card empty"><div class="icon">${icon}</div><h3>${name}</h3><p>${text}</p></div></div>`}
function render(){week.value=state.week;const map={dashboard:['Dashboard',dashboard()],workouts:['Treinos',workoutView()],plan:['Plano',placeholder('Plano','▤','Periodização, semanas, blocos e organização do plano de treino importado do Excel.')],progress:['Progresso',placeholder('Progresso','↗','Volume, cargas, recordes e estimativa de 1RM ao longo do tempo.')],body:['Corpo',placeholder('Corpo','◇','Peso, passos, medidas corporais e evolução semanal.')],nutrition:['Nutrição',placeholder('Nutrição','◉','Macros, calorias, água e acompanhamento nutricional.') ]};title.textContent=map[state.view][0];app.innerHTML=map[state.view][1]}
render();