const app=document.querySelector('#app'),title=document.querySelector('#pageTitle'),week=document.querySelector('#weekSelect');
for(let i=1;i<=PLAN.weeks;i++)week.add(new Option(`Semana ${i}`,i));
let state={view:'dashboard',workout:1,week:1,session:null,exercise:0,libraryQuery:'',libraryGroup:'Todos'};
const STORE='trainlog_sessions_v1';
const sessions=()=>JSON.parse(localStorage.getItem(STORE)||'[]');
const saveSessions=x=>localStorage.setItem(STORE,JSON.stringify(x));
week.onchange=()=>{state.week=+week.value;render()};
document.querySelectorAll('.nav').forEach(n=>n.onclick=()=>{document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));n.classList.add('active');state.view=n.dataset.view;state.session=null;document.querySelector('.sidebar').classList.remove('open');render()});
document.querySelector('#menu').onclick=()=>document.querySelector('.sidebar').classList.toggle('open');
const workouts=()=>PLAN.workouts.map(w=>`<div class="workout-row" onclick="openWorkout(${w.id})"><span class="num">0${w.id}</span><div><b>${w.name}</b><small>${w.focus} · ${w.exercises.length} exercícios</small></div><span class="arrow">›</span></div>`).join('');
function openWorkout(id){state.workout=id;state.view='workouts';state.session=null;document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.view==='workouts'));render()}
function dashboard(){let ss=sessions(),last=ss[0],sets=ss.reduce((a,s)=>a+s.exercises.reduce((b,e)=>b+e.sets.filter(x=>x.done).length,0),0);return `<div class="wrap"><div class="hero"><div><span class="pill">SEMANA ${state.week} · ${PLAN.goal.toUpperCase()}</span><h2>Continua a construir consistência.</h2><p>Regista cada série e acompanha a evolução sem depender da grelha do Excel.</p><button class="primary" onclick="openWorkout(1)">Ver treino →</button></div></div><div class="stats"><div class="stat"><small>SESSÕES GUARDADAS</small><strong>${ss.length}</strong><em>No browser</em></div><div class="stat"><small>SÉRIES REGISTADAS</small><strong>${sets}</strong><em>Total concluído</em></div><div class="stat"><small>ÚLTIMO TREINO</small><strong>${last?last.workoutName:'—'}</strong><em>${last?new Date(last.finishedAt).toLocaleDateString('pt-PT'):'Ainda sem sessões'}</em></div><div class="stat"><small>SEMANA ACTUAL</small><strong>${state.week}</strong><em>de ${PLAN.weeks}</em></div></div><div class="grid2"><div class="card"><h3>Treinos disponíveis</h3>${workouts()}</div><div class="card"><h3>Dados locais</h3><p class="muted">Os treinos concluídos ficam guardados neste browser. Mais tarde adicionamos exportação e sincronização.</p><div class="note">${last?`Última sessão concluída: <b>${last.workoutName}</b>.`:'Quando concluíres o primeiro treino, o histórico começa a ser construído automaticamente.'}</div></div></div></div>`}
function workoutView(){let w=PLAN.workouts.find(x=>x.id===state.workout);return `<div class="wrap"><div class="sectionhead"><div><p class="eyebrow">SEMANA ${state.week}</p><h2>${w.name}</h2><p>${w.focus} · ${w.exercises.length} exercícios</p></div><button class="primary" onclick="startWorkout()">Iniciar treino</button></div><div class="workout-tabs">${PLAN.workouts.map(x=>`<button class="tab ${x.id===w.id?'active':''}" onclick="state.workout=${x.id};render()">${x.name}</button>`).join('')}</div><div class="card">${w.exercises.map((e,i)=>`<div class="exercise"><div><b>${i+1}. ${e.name}${e.warmup?'<span class="badge">BASE</span>':''}</b><small>${e.warmup?'Séries de preparação incluídas':'Exercício de trabalho'}</small></div><div class="metric"><label>Séries</label><span>${e.sets}</span></div><div class="metric"><label>Reps</label><span>${e.reps}</span></div><div class="metric"><label>Carga</label><span>${e.load}</span></div><div class="metric"><label>RPE</label><span>${e.rpe}</span></div><div class="metric"><label>Descanso</label><span>${e.rest}</span></div></div>`).join('')}</div></div>`}
function startWorkout(){let w=PLAN.workouts.find(x=>x.id===state.workout);state.exercise=0;state.session={id:Date.now(),workoutId:w.id,workoutName:w.name,week:state.week,startedAt:new Date().toISOString(),exercises:w.exercises.map(e=>({name:e.name,target:e,sets:Array.from({length:e.sets},()=>({reps:'',load:'',rpe:'',done:false}))}))};state.view='session';render()}
function setVal(si,key,val){state.session.exercises[state.exercise].sets[si][key]=val}
function toggleSet(si){let s=state.session.exercises[state.exercise].sets[si];s.done=!s.done;render()}
function moveExercise(d){state.exercise=Math.max(0,Math.min(state.session.exercises.length-1,state.exercise+d));render()}
function finishWorkout(){if(!confirm('Concluir e guardar este treino?'))return;state.session.finishedAt=new Date().toISOString();let all=sessions();all.unshift(state.session);saveSessions(all);state.session=null;state.view='dashboard';document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.view==='dashboard'));render()}
function sessionView(){let s=state.session,e=s.exercises[state.exercise],t=e.target,done=s.exercises.reduce((a,x)=>a+x.sets.filter(y=>y.done).length,0),total=s.exercises.reduce((a,x)=>a+x.sets.length,0);return `<div class="wrap session-wrap"><div class="session-top"><div><p class="eyebrow">${s.workoutName} · SEMANA ${s.week}</p><h2>${e.name}</h2><p>Exercício ${state.exercise+1} de ${s.exercises.length}</p></div><div class="progress-ring">${done}/${total}<small>séries</small></div></div><div class="session-progress"><span style="width:${total?done/total*100:0}%"></span></div><div class="targetbar"><div><small>ALVO</small><b>${t.sets} × ${t.reps}</b></div><div><small>RPE</small><b>${t.rpe}</b></div><div><small>DESCANSO</small><b>${t.rest}</b></div><div><small>CARGA PLANEADA</small><b>${t.load}</b></div></div><div class="card set-card"><div class="set-head"><span>Série</span><span>Carga (kg)</span><span>Reps</span><span>RPE</span><span></span></div>${e.sets.map((x,i)=>`<div class="set-row ${x.done?'done':''}"><b>${i+1}</b><input type="number" inputmode="decimal" value="${x.load}" placeholder="kg" onchange="setVal(${i},'load',this.value)"><input type="number" inputmode="numeric" value="${x.reps}" placeholder="reps" onchange="setVal(${i},'reps',this.value)"><input type="number" inputmode="decimal" step=".5" min="1" max="10" value="${x.rpe}" placeholder="RPE" onchange="setVal(${i},'rpe',this.value)"><button class="check" onclick="toggleSet(${i})">${x.done?'✓':'○'}</button></div>`).join('')}</div><div class="session-nav"><button class="secondary" onclick="moveExercise(-1)" ${state.exercise===0?'disabled':''}>← Anterior</button>${state.exercise===s.exercises.length-1?'<button class="finish" onclick="finishWorkout()">Concluir treino ✓</button>':'<button class="primary" onclick="moveExercise(1)">Seguinte →</button>'}</div><div class="exercise-dots">${s.exercises.map((x,i)=>`<button onclick="state.exercise=${i};render()" class="${i===state.exercise?'active':''} ${x.sets.every(y=>y.done)?'complete':''}">${i+1}</button>`).join('')}</div></div>`}
function planView(){return `<div class="wrap"><div class="sectionhead"><div><p class="eyebrow">REFERÊNCIAS DO TREINADOR</p><h2>Modelos de treino</h2><p>Os agrupamentos são preservados dos planos originais; não representam histórico de cargas.</p></div></div><div class="template-grid">${TEMPLATES.map(t=>`<article class="template-card"><div class="template-top"><span class="template-number">0${t.id}</span><span class="source-tag">${t.source}</span></div><h3>${t.label}</h3><p>${t.focus}</p><ol>${t.exerciseIds.map(id=>`<li>${ex(id).name}</li>`).join('')}</ol><button class="secondary" onclick="openWorkout(${t.id})">Abrir como treino →</button></article>`).join('')}</div><div class="note">Estes quatro modelos vêm do ficheiro de acompanhamento anterior. Os exercícios adicionais do <b>Peres 2025</b> estão disponíveis na Biblioteca para usarmos na construção de planos novos.</div></div>`}
function libraryView(){let groups=['Todos',...new Set(EXERCISES.map(x=>x.group))],q=state.libraryQuery.toLowerCase(),items=EXERCISES.filter(x=>(state.libraryGroup==='Todos'||x.group===state.libraryGroup)&&x.name.toLowerCase().includes(q));return `<div class="wrap"><div class="sectionhead"><div><p class="eyebrow">DOIS PLANOS · UMA BIBLIOTECA</p><h2>Biblioteca de exercícios</h2><p>${EXERCISES.length} exercícios e variantes retirados dos dois ficheiros Excel.</p></div></div><div class="library-tools"><input id="librarySearch" placeholder="Pesquisar exercício…" value="${state.libraryQuery}" oninput="state.libraryQuery=this.value;render()"><div class="filter-chips">${groups.map(g=>`<button class="${g===state.libraryGroup?'active':''}" onclick="state.libraryGroup='${g}';render()">${g}</button>`).join('')}</div></div><div class="library-grid">${items.map(x=>`<article class="library-card"><div class="muscle">${x.group}</div><h3>${x.name}</h3><span class="source-tag">${x.source}</span></article>`).join('')}</div>${!items.length?'<div class="card empty"><h3>Sem resultados</h3><p>Experimenta outro nome ou grupo muscular.</p></div>':''}</div>`}
function placeholder(name,icon,text){return `<div class="wrap"><div class="sectionhead"><div><h2>${name}</h2><p>Área preparada para a próxima fase.</p></div></div><div class="card empty"><div class="icon">${icon}</div><h3>${name}</h3><p>${text}</p></div></div>`}
function render(){
  week.value=state.week;
  const views={
    dashboard:{title:'Dashboard',view:dashboard},
    workouts:{title:'Treinos',view:workoutView},
    session:{title:'Treino em curso',view:sessionView},
    plan:{title:'Plano',view:planView},
    library:{title:'Biblioteca',view:libraryView},
    progress:{title:'Progresso',view:()=>placeholder('Progresso','↗','Volume, cargas, recordes e estimativa de 1RM ao longo do tempo.')},
    body:{title:'Corpo',view:()=>placeholder('Corpo','◇','Peso, passos, medidas corporais e evolução semanal.')},
    nutrition:{title:'Nutrição',view:()=>placeholder('Nutrição','◉','Macros, calorias, água e acompanhamento nutricional.')}
  };
  const current=views[state.view]||views.dashboard;
  title.textContent=current.title;
  app.innerHTML=current.view();
}
render();