const app=document.querySelector('#app'),title=document.querySelector('#pageTitle'),week=document.querySelector('#weekSelect');
const HELP={
 'Séries':'Número de séries de trabalho previstas para o exercício.',
 'Reps':'Número de repetições a realizar em cada série.',
 'Carga':'Peso utilizado no exercício. Regista a carga em kg quando aplicável.',
 'RPE':'Escala de esforço percebido: 10 = não faço +1 rep nem com mais carga; 9,5 = não faço +1 rep, talvez consiga com mais carga; 9 = faço +1 rep; 8,5 = faço +1 rep, talvez 2; 8 = faço +2 reps; 7 = faço +3 reps; 6 = faço +4 reps.',
 'Descanso':'Tempo de descanso entre séries.'
};
const helpLabel=(label,key=label)=>`<span class="help-label" tabindex="0">${label}<span class="help-icon">?</span><span class="help-tip">${HELP[key]||''}</span></span>`;
for(let i=1;i<=PLAN.weeks;i++)week.add(new Option(`Semana ${i}`,i));
let state={view:'dashboard',workout:1,week:1,session:null,exercise:0,libraryQuery:'',libraryGroup:'Todos',exerciseDetail:null};
const STORE='trainlog_sessions_v1',EX_META_STORE='trainlog_exercise_meta_v1',PLAN_STORE='trainlog_plan_v1';
const DEFAULT_PLAN=JSON.parse(JSON.stringify(PLAN));
const savedPlan=()=>{try{return JSON.parse(localStorage.getItem(PLAN_STORE))}catch(e){return null}};
const storedPlan=savedPlan();if(storedPlan?.workouts?.length)Object.assign(PLAN,storedPlan);
const persistPlan=()=>localStorage.setItem(PLAN_STORE,JSON.stringify(PLAN));
const esc=s=>String(s??'').replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/</g,'&lt;').replace(/>/g,'&gt;');
const exerciseMeta=()=>JSON.parse(localStorage.getItem(EX_META_STORE)||'{}');
const exerciseData=id=>{let base=ex(id),meta=exerciseMeta()[id]||{};return {...base,...meta}};
function saveExerciseMeta(id){
 const all=exerciseMeta(),notes=document.querySelector('#exerciseNotes')?.value.trim()||'',video=document.querySelector('#exerciseVideo')?.value.trim()||'';
 if(video&&!/^https?:\/\//i.test(video)){alert('O link deve começar por http:// ou https://');return}
 all[id]={notes,video};localStorage.setItem(EX_META_STORE,JSON.stringify(all));state.exerciseDetail=id;render()
}
function openExercise(id){state.exerciseDetail=id;render()}
function closeExercise(){state.exerciseDetail=null;render()}
function exercisePanel(){
 if(!state.exerciseDetail)return '';
 const e=exerciseData(state.exerciseDetail);
 return `<div class="detail-overlay" onclick="if(event.target===this)closeExercise()"><aside class="exercise-detail"><button class="detail-close" onclick="closeExercise()">×</button><div class="muscle">${e.group}</div><h2>${e.name}</h2><div class="detail-section"><label>Notas / instruções</label><textarea id="exerciseNotes" rows="6" placeholder="Ex.: posição, amplitude, ritmo, cuidados técnicos…">${e.notes||''}</textarea></div><div class="detail-section"><label>Vídeo ou link de demonstração</label><input id="exerciseVideo" type="url" placeholder="https://…" value="${e.video||''}">${e.video?`<a class="video-link" href="${e.video}" target="_blank" rel="noopener">▶ Ver demonstração</a>`:''}</div><button class="primary detail-save" onclick="saveExerciseMeta('${e.id}')">Guardar alterações</button></aside></div>`
}
const sessions=()=>JSON.parse(localStorage.getItem(STORE)||'[]');
const saveSessions=x=>localStorage.setItem(STORE,JSON.stringify(x));
week.onchange=()=>{state.week=+week.value;render()};
document.querySelectorAll('.nav').forEach(n=>n.onclick=()=>{document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));n.classList.add('active');state.view=n.dataset.view;state.session=null;document.querySelector('.sidebar').classList.remove('open');render()});
document.querySelector('#menu').onclick=()=>document.querySelector('.sidebar').classList.toggle('open');
const workouts=()=>PLAN.workouts.map(w=>`<div class="workout-row" onclick="openWorkout(${w.id})"><span class="num">0${w.id}</span><div><b>${w.name}</b><small>${w.focus} · ${w.exercises.length} exercícios</small></div><span class="arrow">›</span></div>`).join('');
function openWorkout(id){state.workout=id;state.view='workouts';state.session=null;document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.view==='workouts'));render()}
function dashboard(){let ss=sessions(),last=ss[0],sets=ss.reduce((a,s)=>a+s.exercises.reduce((b,e)=>b+e.sets.filter(x=>x.done).length,0),0);return `<div class="wrap"><div class="hero"><div><span class="pill">SEMANA ${state.week} · ${PLAN.goal.toUpperCase()}</span><h2>Continua a construir consistência.</h2><p>Regista cada série e acompanha a evolução do teu plano de treino.</p><button class="primary" onclick="openWorkout(1)">Ver treino →</button></div></div><div class="stats"><div class="stat"><small>SESSÕES GUARDADAS</small><strong>${ss.length}</strong><em>No browser</em></div><div class="stat"><small>SÉRIES REGISTADAS</small><strong>${sets}</strong><em>Total concluído</em></div><div class="stat"><small>ÚLTIMO TREINO</small><strong>${last?last.workoutName:'—'}</strong><em>${last?new Date(last.finishedAt).toLocaleDateString('pt-PT'):'Ainda sem sessões'}</em></div><div class="stat"><small>SEMANA ACTUAL</small><strong>${state.week}</strong><em>de ${PLAN.weeks}</em></div></div><div class="grid2"><div class="card"><h3>Treinos disponíveis</h3>${workouts()}</div><div class="card"><h3>Dados locais</h3><p class="muted">Os treinos concluídos ficam guardados neste browser. Mais tarde adicionamos exportação e sincronização.</p><div class="note">${last?`Última sessão concluída: <b>${last.workoutName}</b>.`:'Quando concluíres o primeiro treino, o histórico começa a ser construído automaticamente.'}</div></div></div></div>`}
function workoutView(){let w=PLAN.workouts.find(x=>x.id===state.workout)||PLAN.workouts[0];state.workout=w.id;return `<div class="wrap"><div class="sectionhead"><div><p class="eyebrow">SEMANA ${state.week}</p><h2>${w.name}</h2><p>${w.focus} · ${w.exercises.length} exercícios</p></div><button class="primary" onclick="startWorkout()">Iniciar treino</button></div><div class="workout-tabs">${PLAN.workouts.map(x=>`<button class="tab ${x.id===w.id?'active':''}" onclick="state.workout=${x.id};render()">${x.name}</button>`).join('')}</div><div class="card">${w.exercises.map((e,i)=>`<div class="exercise"><div class="exercise-name" onclick="openExercise('${e.id}')"><b>${i+1}. ${e.name}${e.warmup?'<span class="badge">BASE</span>':''}</b><small>${e.warmup?'Séries de preparação incluídas':'Exercício de trabalho'}</small></div><div class="metric"><label>${helpLabel('Séries')}</label><span>${e.sets}</span></div><div class="metric"><label>${helpLabel('Reps')}</label><span>${e.reps}</span></div><div class="metric"><label>${helpLabel('Carga')}</label><span>${e.load}</span></div><div class="metric"><label>${helpLabel('RPE')}</label><span>${e.rpe}</span></div><div class="metric"><label>${helpLabel('Descanso')}</label><span>${e.rest}</span></div></div>`).join('')}</div></div>`}
function startWorkout(){let w=PLAN.workouts.find(x=>x.id===state.workout)||PLAN.workouts[0];state.exercise=0;state.session={id:Date.now(),workoutId:w.id,workoutName:w.name,week:state.week,startedAt:new Date().toISOString(),exercises:w.exercises.map(e=>({name:e.name,target:e,sets:Array.from({length:e.sets},()=>({reps:'',load:'',rpe:'',done:false}))}))};state.view='session';render()}
function setVal(si,key,val){state.session.exercises[state.exercise].sets[si][key]=val}
function toggleSet(si){let s=state.session.exercises[state.exercise].sets[si];s.done=!s.done;render()}
function moveExercise(d){state.exercise=Math.max(0,Math.min(state.session.exercises.length-1,state.exercise+d));render()}
function finishWorkout(){if(!confirm('Concluir e guardar este treino?'))return;state.session.finishedAt=new Date().toISOString();let all=sessions();all.unshift(state.session);saveSessions(all);state.session=null;state.view='dashboard';document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.view==='dashboard'));render()}
function sessionView(){let s=state.session,e=s.exercises[state.exercise],t=e.target,done=s.exercises.reduce((a,x)=>a+x.sets.filter(y=>y.done).length,0),total=s.exercises.reduce((a,x)=>a+x.sets.length,0);return `<div class="wrap session-wrap"><div class="session-top"><div><p class="eyebrow">${s.workoutName} · SEMANA ${s.week}</p><h2>${e.name}</h2><p>Exercício ${state.exercise+1} de ${s.exercises.length}</p></div><div class="progress-ring">${done}/${total}<small>séries</small></div></div><div class="session-progress"><span style="width:${total?done/total*100:0}%"></span></div><div class="targetbar"><div><small>ALVO</small><b>${t.sets} × ${t.reps}</b></div><div><small>${helpLabel('RPE')}</small><b>${t.rpe}</b></div><div><small>${helpLabel('DESCANSO','Descanso')}</small><b>${t.rest}</b></div><div><small>${helpLabel('CARGA PLANEADA','Carga')}</small><b>${t.load}</b></div></div><div class="card set-card"><div class="set-head"><span>Série</span><span>${helpLabel('Carga (kg)','Carga')}</span><span>${helpLabel('Reps')}</span><span>${helpLabel('RPE')}</span><span></span></div>${e.sets.map((x,i)=>`<div class="set-row ${x.done?'done':''}"><b>${i+1}</b><input type="number" inputmode="decimal" value="${x.load}" placeholder="kg" onchange="setVal(${i},'load',this.value)"><input type="number" inputmode="numeric" value="${x.reps}" placeholder="reps" onchange="setVal(${i},'reps',this.value)"><input type="number" inputmode="decimal" step=".5" min="1" max="10" value="${x.rpe}" placeholder="RPE" onchange="setVal(${i},'rpe',this.value)"><button class="check" onclick="toggleSet(${i})">${x.done?'✓':'○'}</button></div>`).join('')}</div><div class="session-nav"><button class="secondary" onclick="moveExercise(-1)" ${state.exercise===0?'disabled':''}>← Anterior</button>${state.exercise===s.exercises.length-1?'<button class="finish" onclick="finishWorkout()">Concluir treino ✓</button>':'<button class="primary" onclick="moveExercise(1)">Seguinte →</button>'}</div><div class="exercise-dots">${s.exercises.map((x,i)=>`<button onclick="state.exercise=${i};render()" class="${i===state.exercise?'active':''} ${x.sets.every(y=>y.done)?'complete':''}">${i+1}</button>`).join('')}</div></div>`}
function planView(){
 return `<div class="wrap"><div class="sectionhead"><div><p class="eyebrow">PLANO ACTUAL</p><h2>Editor de plano</h2><p>Configura os treinos que aparecem na área Treinos.</p></div><button class="primary" onclick="newWorkout()">+ Novo treino</button></div><div class="plan-editor">${PLAN.workouts.map((w,wi)=>`<article class="edit-workout"><div class="edit-workout-head"><div class="edit-fields"><input class="edit-title" value="${esc(w.name)}" onchange="editWorkout(${wi},'name',this.value)" aria-label="Nome do treino"><input value="${esc(w.focus)}" onchange="editWorkout(${wi},'focus',this.value)" placeholder="Foco do treino" aria-label="Foco do treino"></div><div class="edit-actions"><button onclick="duplicateWorkout(${wi})">Duplicar</button><button class="danger-text" onclick="deleteWorkout(${wi})">Eliminar</button></div></div><div class="edit-exercises">${w.exercises.map((e,ei)=>`<div class="edit-exercise"><div class="edit-ex-name"><span class="drag">⋮⋮</span><button class="link-button" onclick="openExercise('${e.id}')">${ei+1}. ${e.name}</button></div><label>Séries<input type="number" min="1" max="20" value="${e.sets}" onchange="editExercise(${wi},${ei},'sets',this.value)"></label><label>Reps<input value="${esc(e.reps)}" onchange="editExercise(${wi},${ei},'reps',this.value)"></label><label>RPE<input type="number" min="1" max="10" step=".5" value="${e.rpe}" onchange="editExercise(${wi},${ei},'rpe',this.value)"></label><label>Descanso<input value="${esc(e.rest)}" onchange="editExercise(${wi},${ei},'rest',this.value)"></label><label>Carga<input value="${esc(e.load)}" onchange="editExercise(${wi},${ei},'load',this.value)"></label><div class="row-actions"><button onclick="movePlanExercise(${wi},${ei},-1)" ${ei===0?'disabled':''}>↑</button><button onclick="movePlanExercise(${wi},${ei},1)" ${ei===w.exercises.length-1?'disabled':''}>↓</button><button class="remove" onclick="removePlanExercise(${wi},${ei})">×</button></div></div>`).join('')}</div><div class="add-exercise"><select id="add-${wi}"><option value="">Adicionar exercício da Biblioteca…</option>${EXERCISES.filter(x=>!w.exercises.some(e=>e.id===x.id)).map(x=>`<option value="${x.id}">${x.group} — ${x.name}</option>`).join('')}</select><button class="secondary" onclick="addPlanExercise(${wi})">Adicionar</button></div></article>`).join('')}</div><div class="plan-footer"><button class="secondary" onclick="resetPlan()">Repor plano inicial</button><span>As alterações são guardadas automaticamente neste browser.</span></div></div>`
}
function editWorkout(wi,key,value){PLAN.workouts[wi][key]=value;persistPlan()}
function editExercise(wi,ei,key,value){PLAN.workouts[wi].exercises[ei][key]=key==='sets'?Math.max(1,+value||1):value;persistPlan()}
function addPlanExercise(wi){let sel=document.querySelector('#add-'+wi),base=ex(sel.value);if(!base)return;PLAN.workouts[wi].exercises.push({...base,sets:3,reps:'12–15',load:'Registar',rpe:7,rest:'1:30'});persistPlan();render()}
function removePlanExercise(wi,ei){PLAN.workouts[wi].exercises.splice(ei,1);persistPlan();render()}
function movePlanExercise(wi,ei,d){let a=PLAN.workouts[wi].exercises,j=ei+d;if(j<0||j>=a.length)return;[a[ei],a[j]]=[a[j],a[ei]];persistPlan();render()}
function duplicateWorkout(wi){let copy=JSON.parse(JSON.stringify(PLAN.workouts[wi]));copy.id=Date.now();copy.name=copy.name+' (cópia)';PLAN.workouts.splice(wi+1,0,copy);persistPlan();render()}
function newWorkout(){let id=Date.now();PLAN.workouts.push({id,name:'Novo treino',focus:'',exercises:[]});persistPlan();state.workout=id;render()}
function deleteWorkout(wi){if(PLAN.workouts.length===1){alert('O plano tem de ter pelo menos um treino.');return}if(!confirm('Eliminar este treino do plano?'))return;let id=PLAN.workouts[wi].id;PLAN.workouts.splice(wi,1);if(state.workout===id)state.workout=PLAN.workouts[0].id;persistPlan();render()}
function resetPlan(){if(!confirm('Repor o plano inicial? As alterações feitas ao plano serão perdidas.'))return;PLAN.name=DEFAULT_PLAN.name;PLAN.goal=DEFAULT_PLAN.goal;PLAN.weeks=DEFAULT_PLAN.weeks;PLAN.workouts=JSON.parse(JSON.stringify(DEFAULT_PLAN.workouts));persistPlan();state.workout=PLAN.workouts[0].id;render()}
function libraryView(){let groups=['Todos',...new Set(EXERCISES.map(x=>x.group))],q=state.libraryQuery.toLowerCase(),items=EXERCISES.filter(x=>(state.libraryGroup==='Todos'||x.group===state.libraryGroup)&&x.name.toLowerCase().includes(q));return `<div class="wrap"><div class="sectionhead"><div><p class="eyebrow">EXERCÍCIOS</p><h2>Biblioteca de exercícios</h2><p>${EXERCISES.length} exercícios e variantes disponíveis.</p></div></div><div class="library-tools"><input id="librarySearch" placeholder="Pesquisar exercício…" value="${state.libraryQuery}" oninput="state.libraryQuery=this.value;render()"><div class="filter-chips">${groups.map(g=>`<button class="${g===state.libraryGroup?'active':''}" onclick="state.libraryGroup='${g}';render()">${g}</button>`).join('')}</div></div><div class="library-grid">${items.map(x=>`<article class="library-card clickable" onclick="openExercise('${x.id}')"><div class="muscle">${x.group}</div><h3>${x.name}</h3><small>Ver ficha →</small></article>`).join('')}</div>${!items.length?'<div class="card empty"><h3>Sem resultados</h3><p>Experimenta outro nome ou grupo muscular.</p></div>':''}</div>`}
function placeholder(name,icon,text){return `<div class="wrap"><div class="sectionhead"><div><h2>${name}</h2><p>Área preparada para a próxima fase.</p></div></div><div class="card empty"><div class="icon">${icon}</div><h3>${name}</h3><p>${text}</p></div></div>`}
function render(){
  week.value=state.week;
  const views={
    dashboard:{title:'Dashboard',view:dashboard},
    workouts:{title:'Treinos',view:workoutView},
    session:{title:'Treino em curso',view:sessionView},
    plan:{title:'Plano',view:planView},
    library:{title:'Biblioteca',view:libraryView},
    progress:{title:'Progresso',view:()=>placeholder('Progresso','↗','Volume, cargas, recordes e estimativa de 1RM ao longo do tempo.')},
    body:{title:'Corpo',view:()=>placeholder('Corpo','◇','Peso, passos, medidas corporais e evolução semanal.')},
    nutrition:{title:'Nutrição',view:()=>placeholder('Nutrição','◉','Macros, calorias, água e acompanhamento nutricional.')}
  };
  const current=views[state.view]||views.dashboard;
  title.textContent=current.title;
  app.innerHTML=current.view()+exercisePanel();
}
render();