const EXERCISES=[
{notes:'',video:'',id:'bench',name:'Supino com barra',group:'Peito'},{notes:'',video:'',id:'ohp',name:'Press de ombros com barra',group:'Ombros'},{notes:'',video:'',id:'ohp-seated',name:'Press de ombros sentado com barra',group:'Ombros'},{notes:'',video:'',id:'incline-db',name:'Supino inclinado com halteres 15°',group:'Peito'},{notes:'',video:'',id:'incline-bb',name:'Supino inclinado com barra',group:'Peito'},{notes:'',video:'',id:'fly',name:'Aberturas inclinadas com halteres 15°',group:'Peito'},{notes:'',video:'',id:'lateral',name:'Elevações laterais com halteres',group:'Ombros'},{notes:'',video:'',id:'triceps-rope',name:'Tríceps com corda nos cabos',group:'Tríceps'},{notes:'',video:'',id:'skull',name:'Skull Crushers',group:'Tríceps'},{notes:'',video:'',id:'row-bb',name:'Remada com barra',group:'Costas'},{notes:'',video:'',id:'pulldown',name:'Puxador alto',group:'Costas'},{notes:'',video:'',id:'row-cable',name:'Remada nos cabos',group:'Costas'},{notes:'',video:'',id:'row-db',name:'Remada unilateral com halteres',group:'Costas'},{notes:'',video:'',id:'row-machine',name:'Remada na máquina unilateral',group:'Costas'},{notes:'',video:'',id:'rear-fly',name:'Voos com halteres',group:'Ombros'},{notes:'',video:'',id:'facepull',name:'Rope Facepulls',group:'Ombros'},{notes:'',video:'',id:'curl-cable',name:'Bíceps curl nos cabos',group:'Bíceps'},{notes:'',video:'',id:'curl-bb',name:'Bíceps com barra',group:'Bíceps'},{notes:'',video:'',id:'curl-alt',name:'Bíceps alternado com halteres',group:'Bíceps'},{notes:'',video:'',id:'squat',name:'Agachamento com barra',group:'Pernas'},{notes:'',video:'',id:'deadlift',name:'Peso morto',group:'Pernas'},{notes:'',video:'',id:'lunges',name:'Lunges com o pé da frente elevado',group:'Pernas'},{notes:'',video:'',id:'rdl',name:'Stiff / Romanian Deadlift',group:'Pernas'},{notes:'',video:'',id:'bulgarian',name:'Bulgarians',group:'Pernas'},{notes:'',video:'',id:'single-hip',name:'Single Leg Hip Extension no banco',group:'Glúteos'},{notes:'',video:'',id:'hip-floor',name:'Hip Extensions no chão',group:'Glúteos'},{notes:'',video:'',id:'calf',name:'Gémeo em pé unilateral',group:'Pernas'},{notes:'',video:'',id:'knee',name:'Hanging Knee Raise',group:'Core'},{notes:'',video:'',id:'chin-pull',name:'Puxador alto com pega em supinação',group:'Costas'},{notes:'',video:'',id:'pushup',name:'Flexões no banco ou na barra',group:'Peito'},{notes:'',video:'',id:'chest-row',name:'Remada com halteres com peito apoiado no banco',group:'Costas'}];
const TEMPLATES=[
{notes:'',video:'',id:1,name:'Treino 1',label:'Push',focus:'Peito · Ombros · Tríceps',exerciseIds:['bench','ohp','incline-db','fly','lateral','triceps-rope']},
{notes:'',video:'',id:2,name:'Treino 2',label:'Pull',focus:'Costas · Ombros posteriores · Bíceps',exerciseIds:['row-bb','pulldown','row-cable','row-db','rear-fly','curl-cable']},
{notes:'',video:'',id:3,name:'Treino 3',label:'Pernas + Core',focus:'Pernas · Glúteos · Core',exerciseIds:['squat','deadlift','lunges','rdl','calf','knee']},
{notes:'',video:'',id:4,name:'Treino 4',label:'Upper misto',focus:'Peito · Costas · Braços · Ombros',exerciseIds:['incline-bb','chin-pull','pushup','chest-row','skull','curl-alt','lateral']}];
const ex=id=>EXERCISES.find(x=>x.id===id);
const makeWorkout=t=>({notes:'',video:'',id:t.id,name:t.name,focus:t.focus,exercises:t.exerciseIds.map(id=>({...ex(id),sets:3,reps:'12–15',load:'Registar',rpe:7,rest:'1:30'}))});
const PLAN={name:'Plano actual',goal:'Hipertrofia / Força',weeks:12,workouts:TEMPLATES.map(makeWorkout)};